=== sergei-doroshenko/it-spring/src/main/resources/xml/type.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.w3schools.com"
	xmlns="http://www.w3schools.com"
	elementFormDefault="qualified">
	<xs:element name="types">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="type" type="issuetype" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="issuetype">
		<xs:sequence>
			<xs:element name="id" type="xs:integer"/>
			<xs:element name="name" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== sergei-doroshenko/it-spring/src/main/resources/xml/types.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:types xmlns:p="http://www.w3schools.com" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.w3schools.com ../../../../target/classes/xml/type.xsd ">
  <p:type>
    <p:id>1</p:id>
    <p:name>COSMETIC</p:name>
  </p:type>
  <p:type>
    <p:id>2</p:id>
    <p:name>BUG</p:name>
  </p:type>
  <p:type>
    <p:id>3</p:id>
    <p:name>FEATURE</p:name>
  </p:type>
  <p:type>
    <p:id>4</p:id>
    <p:name>PERFOMANCE</p:name>
  </p:type>
</p:types>
